---
# tasks file for tomcat
- name: Configure temporary _server.xml_ configuration file. This one will be copied over server.xml
  block:
    - name: Setup temp server.xml
      template:
        src: "{{ tomcat_template_server }}"
        dest: "{{ tomcat_install_path }}/conf/_server.xml_"
      changed_when: False

    - name: Set Engine extra conf
      xml:
        path: "{{ tomcat_install_path }}/conf/_server.xml_"
        xpath: '//Service/Engine[@name="Catalina"]'
        attribute: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ tomcat_server_engine_extra_conf }}"
      changed_when: False

    - name: Set AJP connector extra conf
      xml:
        path: "{{ tomcat_install_path }}/conf/_server.xml_"
        xpath: '//Service/Connector[@protocol="AJP/1.3"]'
        attribute: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ tomcat_server_ajp_extra_conf }}"
      changed_when: False

    - name: Set HTTP connector extra conf
      xml:
        path: "{{ tomcat_install_path }}/conf/_server.xml_"
        xpath: '//Service/Connector[@protocol="HTTP/1.1"]'
        attribute: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ tomcat_server_http_extra_conf }}"
      changed_when: False

    - name: Copy temp server.xml
      copy:
        src: "{{ tomcat_install_path }}/conf/_server.xml_"
        dest: "{{ tomcat_install_path }}/conf/server.xml"
        remote_src: yes
        force: yes
      notify: Restart tomcat

    - name: Remove temp server.xml
      file:
        path: "{{ tomcat_install_path }}/conf/_server.xml_"
        state: absent
      changed_when: False

- name: Set fact of user roles to be enabled
  set_fact:
    tomcat_user_roles: "{{ (tomcat_user_roles + item.roles.split(',')|list)|unique }}"
  with_items:
    - "{{ tomcat_users }}"

- name: Setup tomcat-users.xml
  template:
    src: "{{ tomcat_template_users }}"
    dest: "{{ tomcat_install_path }}/conf/tomcat-users.xml"
  notify: Restart tomcat

- name: Stat Manager app
  stat:
    path: "{{ tomcat_install_path }}/webapps/manager/META-INF/context.xml"
  register: tomcat_stat_manager

- name: Configure access to Manager app (from localhost only or from anywhere)
  template:
    src: "{{ tomcat_template_manager_context }}"
    dest: "{{ tomcat_install_path }}/webapps/manager/META-INF/context.xml"
  notify: Restart tomcat
  when: tomcat_stat_manager.stat.exists|bool

- name: Stat Host Manager
  stat:
    path: "{{ tomcat_install_path }}/webapps/host-manager/META-INF/context.xml"
  register: tomcat_stat_host_manager

- name: Configure access to Host Manager (from localhost only or from anywhere)
  template:
    src: "{{ tomcat_template_host_manager_context }}"
    dest: "{{ tomcat_install_path }}/webapps/host-manager/META-INF/context.xml"
  notify: Restart tomcat
- name: Configure setenv.sh
  template:
    src: "{{ tomcat_template_setenv }}"
    dest: "{{ tomcat_install_path }}/{{ tomcat_service_name }}/bin/setenv.sh"
  notify: Restart tomcat
