---
- name: Get services
  ansible.builtin.service_facts:

- name: Stop tomcat if changing version
  ansible.builtin.service:
    name: "{{ tomcat_service_name }}"
    state: stopped
  when: ansible_facts.services[tomcat_service_name + '.service'] is defined

- name: Create group {{ tomcat_user_group }}
  ansible.builtin.group:
    name: "{{ tomcat_user_group }}"
    gid: "{{ tomcat_user_group_gid | default(omit, true) }}"
    state: present

- name: Create user {{ tomcat_user }}
  ansible.builtin.user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    uid: "{{ tomcat_user_uid | default(omit, true) }}"
    createhome: false
    system: true
    shell: /sbin/nologin
    state: present

- name: Create temporary directory for downloading tomcat tgz
  ansible.builtin.tempfile:
    state: directory
    prefix: "tomcat-install-"
  register: tomcat_tempdir
  notify: Remove tomcat tempdir

- name: Download apache-tomcat-{{ tomcat_version }}.tar.gz
  ansible.builtin.get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_tempdir.path }}"
    mode: 0640
    timeout: 120

- name: Ensure tomcat_base_path {{ tomcat_base_path }} exists
  ansible.builtin.file:
    path: "{{ tomcat_base_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz to {{ tomcat_install_path }}
  ansible.builtin.unarchive:
    src: "{{ tomcat_tempdir.path }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_base_path }}"
    remote_src: true
    owner: "{{ tomcat_set_production | ternary('root', tomcat_user) }}"
    group: "{{ tomcat_user_group }}"
    creates: "{{ tomcat_install_path }}"
    extra_opts:
      - --transform
      - s#apache-tomcat-{{ tomcat_version }}#{{ _tomcat_instance_prefix + 'apache-tomcat-' + tomcat_version }}#

- name: Create symlink {{ tomcat_install_path }} to {{ tomcat_base_path }}/{{ tomcat_service_name }}
  ansible.builtin.file:
    src: "{{ tomcat_install_path }}"
    dest: "{{ tomcat_install_path_link }}"
    state: link
