---
- name: Get services
  ansible.builtin.service_facts:

- name: Check in tomcat is installed, checking if link to tomcat exists
  ansible.builtin.stat:
    path: "{{ tomcat_install_path_link }}"
  register: tomcat_is_installed

- name: Set previous version path
  ansible.builtin.set_fact:
    tomcat_previous_version_path: "{{ tomcat_is_installed.stat.lnk_source is defined | ternary(tomcat_is_installed.stat.lnk_source, tomcat_is_installed.stat.path | default('')) }}"

- name: Install Java
  ansible.builtin.package:
    name: "{{ tomcat_java_packages }}"
    state: present
  when: tomcat_install_java
  notify: Restart tomcat

- name: Install tomcat
  ansible.builtin.import_tasks: install.yml
  when:
    - tomcat_state == "present"
    - tomcat_previous_version_path != tomcat_install_path
  tags:
    - tomcat-install

- name: Configure tomcat
  ansible.builtin.import_tasks: configure.yml
  when: tomcat_state == "present"
  tags:
    - tomcat-config

- name: Stat tomcat install path
  ansible.builtin.stat:
    path: "{{ tomcat_install_path }}"
  register: tomcat_is_installed

- name: Migrate old tomcat
  ansible.builtin.import_tasks: migrate.yml
  when:
    - tomcat_migrate
    - tomcat_state == "present"
    - tomcat_previous_version_path | length > 0 or tomcat_migrate_from_path | length > 0
    - tomcat_previous_version_path != tomcat_install_path
  tags: tomcat-migrate

- name: Set hardening
  ansible.builtin.import_tasks: hardening.yml
  when:
    - tomcat_state == "present"
  notify: Restart tomcat

- name: Uninstall tomcat
  ansible.builtin.import_tasks: uninstall.yml
  when:
    - tomcat_state == "absent"
