---
# tasks file for tomcat
- name: Install tomcat
  include: install.yml
  when: tomcat_state == "present"
  tags: tomcat-install

- name: Configure tomcat
  include: configure.yml
  when: tomcat_state == "present"
  tags: tomcat-config

- name: Custom configuration tomcat
  include: custom.yml
  when: tomcat_state == "present"
  tags: tomcat-custom

- name: Uninstall tomcat
  include: uninstall.yml
  when: tomcat_state == "absent"
