---
# tasks file for tomcat
- name: Stat previous tomcat path
  stat:
    path: "{{ tomcat_base_path }}/{{ tomcat_service_name }}"
  register: tomcat_stat_previous_version
  when:
    - tomcat_upgrade | bool
    - tomcat_state == "present"
  tags: tomcat-upgrade

- name: Install tomcat
  include: install.yml
  when: tomcat_state == "present"
  tags: tomcat-install

- name: Configure tomcat
  include: configure.yml
  when: tomcat_state == "present"
  tags: tomcat-config

- name: Custom configuration tomcat
  include: custom.yml
  when: tomcat_state == "present"
  tags: tomcat-custom

- name: Uninstall tomcat
  include: uninstall.yml
  when: tomcat_state == "absent"

- name: Upgrade tomcat
  include: upgrade.yml
  when:
    - tomcat_upgrade | bool
    - tomcat_state == "present"
  tags: tomcat-upgrade
