---
- name: Set owner and group for non-production installation
  ansible.builtin.file:
    path: "{{ tomcat_install_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    recurse: yes

- name: Set directories permissions for non-production installation
  ansible.builtin.command: find {{ tomcat_install_path }} -type d -exec chmod -c 2750 {} \;
  register: find_chmod_result
  changed_when: find_chmod_result.stdout | length > 0

- name: Set files permissions for non-production installation
  ansible.builtin.command: find {{ tomcat_install_path }} -type f -not -name "*.sh" -exec chmod -c 0640 {} \;
  register: find_chmod_result
  changed_when: find_chmod_result.stdout | length > 0

- name: Set files permissions for non-production installation script files
  ansible.builtin.command: find {{ tomcat_install_path }}/bin -type f -name "*.sh" -exec chmod -c 0750 {} \;
  register: find_chmod_result
  changed_when: find_chmod_result.stdout | length > 0
