---
- name: (uninstall) Check if tomcat service is installed
  ansible.builtin.stat:
    path: "{{ tomcat_systemd_config_path }}/{{ tomcat_service_name }}.service"
  register: tomcat_service_installed

- name: (uninstall) Stop tomcat service if running
  ansible.builtin.service:
    name: "{{ tomcat_service_name }}"
    enabled: no
    state: stopped
  when: tomcat_service_installed.stat.exists

- name: (uninstall) Remove service file {{ tomcat_service_name }}.service
  ansible.builtin.file:
    path: "{{ tomcat_systemd_config_path }}/{{ tomcat_service_name }}.service"
    state: absent

- name: (uninstall) Perform systemctl daemon-reload
  ansible.builtin.service:
    daemon_reload: yes
  changed_when: false

- name: (uninstall) Check if tomcat is installed
  ansible.builtin.stat:
    path: "{{ tomcat_install_path }}"
  register: tomcat_is_installed

- name: (uninstall) Remove symlink {{ tomcat_install_path_link }}
  ansible.builtin.file:
    path: "{{ tomcat_install_path_link }}"
    state: absent

- name: (uninstall) Create backup archive before deletion at {{ tomcat_base_path }}/tomcat-backup-XXX.tgz
  ansible.builtin.archive:
    path: "{{ tomcat_install_path }}"
    dest: "{{ tomcat_base_path }}/tomcat-backup-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.tgz"
    owner: root
    group: root
    mode: 0640
  when:
    - tomcat_uninstall_create_backup
    - tomcat_is_installed.stat.exists

- name: (uninstall) Remove {{ tomcat_install_path }}
  ansible.builtin.file:
    path: "{{ tomcat_install_path }}"
    state: absent

- name: (uninstall) Check if /var/log/{{ tomcat_service_name }} exists
  ansible.builtin.stat:
    path: /var/log/{{ tomcat_service_name }}
  register: tomcat_stat_vlog

- name: (uninstall) Create logs backup archive before deletion at {{ tomcat_base_path }}/tomcat-backup-logs-XXX.tgz
  ansible.builtin.archive:
    path: /var/log/{{ tomcat_service_name }}
    dest: "{{ tomcat_base_path }}/tomcat-backup-logs-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.tgz"
    owner: root
    group: root
    mode: 0640
  when:
    - tomcat_uninstall_create_backup
    - tomcat_stat_vlog.stat.exists

- name: (uninstall) Remove /var/log/{{ tomcat_service_name }}
  ansible.builtin.file:
    path: /var/log/{{ tomcat_service_name }}
    state: absent

- name: (uninstall) Delete user {{ tomcat_user }}
  ansible.builtin.user:
    name: "{{ tomcat_user }}"
    state: absent
    force: yes
  when:
    - tomcat_uninstall_remove_all or tomcat_uninstall_remove_user

- name: (uninstall) Delete group {{ tomcat_user_group }}
  ansible.builtin.group:
    name: "{{ tomcat_user_group }}"
    state: absent
  when:
    - tomcat_uninstall_remove_all or tomcat_uninstall_remove_group

- name: (uninstall) Uninstall Java
  ansible.builtin.package:
    name: "{{ item.package }}"
    state: absent
  loop: "{{ tomcat_java_packages }}"
  when:
    - tomcat_uninstall_remove_all or tomcat_uninstall_remove_java
