---
- name: Find conf in old tomcat path
  find:
    paths:
      - "{{ tomcat_previous_version_path }}/conf"
    file_type: any
  register: tomcat_upgrade_from_conf

- name: Copy conf from old to new - no force
  copy:
    src: "{{ item }}"
    dest: "{{ tomcat_install_path }}/conf/"
    remote_src: yes
    owner: root
    group: "{{ tomcat_user_group }}"
    mode: o-rwx
    force: no
  loop: "{{ tomcat_upgrade_from_conf.files | map(attribute='path') | list }}"
  notify: Restart tomcat

- name: Copy conf from old to new - force
  copy:
    src: "{{ tomcat_previous_version_path }}/conf/{{ item }}"
    dest: "{{ tomcat_install_path }}/conf/"
    remote_src: yes
    owner: root
    group: "{{ tomcat_user_group }}"
    mode: o-rwx
    force: yes
  loop: "{{ tomcat_upgrade_conf_copy_force }}"
  notify: Restart tomcat

- name: Find lib in old tomcat path
  find:
    paths:
      - "{{ tomcat_previous_version_path }}/lib"
    file_type: any
  register: tomcat_upgrade_from_lib

- name: Copy lib from old to new - no force
  copy:
    src: "{{ item }}"
    dest: "{{ tomcat_install_path }}/lib/"
    remote_src: yes
    owner: root
    group: "{{ tomcat_user_group }}"
    mode: o-rwx
    force: no
  loop: "{{ tomcat_upgrade_from_lib.files | map(attribute='path') | list }}"
  notify: Restart tomcat

- name: Find deployed webapps
  find:
    paths:
      - "{{ tomcat_previous_version_path }}/webapps"
    file_type: file
  register: tomcat_upgrade_from_webapps

- name: Copy webapps from old to new
  copy:
    src: "{{ item }}"
    dest: "{{ tomcat_install_path }}/webapps/"
    remote_src: yes
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    mode: o-rwx
  loop: "{{ tomcat_upgrade_from_webapps.files | map(attribute='path') | list }}"

- name: Find extra folders in old
  find:
    paths: "{{ tomcat_previous_version_path }}"
    file_type: directory
  register: tomcat_upgrade_extra_folders_old

- name: Find extra folders in new
  find:
    paths: "{{ tomcat_install_path }}"
    file_type: directory
  register: tomcat_upgrade_extra_folders_new

- name: Set difference for extra config folders
  set_fact:
    tomcat_upgrade_extra_folders_diff: "{{ tomcat_upgrade_extra_folders_old.files|map(attribute='path')|map('regex_replace','.*/','')|list|difference(tomcat_upgrade_extra_folders_new.files|map(attribute='path')|map('regex_replace','.*/','')|list) }}"

- name: Copy extra folders from old to new
  copy:
    src: "{{ tomcat_previous_version_path + '/' + item }}"
    dest: "{{ tomcat_install_path }}/"
    remote_src: yes
    owner: root
    group: "{{ tomcat_user_group }}"
    mode: o-rwx
  loop: "{{ tomcat_upgrade_extra_folders_diff }}"

- name: Backup/Archive old path
  block:
    - name: Archive old path
      archive:
        path: "{{ tomcat_previous_version_path }}"
        dest: "{{ tomcat_previous_version_path }}.tgz"
        owner: root
        group: root
        mode: o-rwx

    - name: Remove old path
      file:
        path: "{{ tomcat_previous_version_path }}"
        state: absent
  when: tomcat_upgrade_archive_old_path|bool
