---
# handlers file for tomcat

- name: restart tomcat
  systemd:
    name: "{{ tomcat_service_name }}"
    state: restarted
    daemon_reload: yes

- name: remove-tomcat_tempdir
  file:
    path: "{{ tomcat_tempdir.path }}"
    state: absent
