---
# handlers file for tomcat

- name: Restart tomcat
  ansible.builtin.service:
    name: "{{ tomcat_service_name }}"
    state: restarted
    daemon_reload: yes

- name: Remove tomcat tempdir
  ansible.builtin.file:
    path: "{{ tomcat_tempdir.path }}"
    state: absent
