---
- name: Reload systemd daemon
  ansible.builtin.service:
    daemon_reload: yes

- name: Restart tomcat
  ansible.builtin.service:
    name: "{{ tomcat_service_name }}"
    state: restarted

- name: Remove tomcat tempdir
  ansible.builtin.file:
    path: "{{ tomcat_tempdir.path }}"
    state: absent
